### ISSUE TITLE
reenter username typo

### ISSUE THREAD

**Issue by Jrawke** [Jrawke/mumbleExpress#17]
[ 18:36 ] MumbleExpress : Enter server address
[ 18:37 ] MumbleExpress : Enter port (if blank, will be default of 64738)
[ 18:37 ] MumbleExpress : Enter user name
[ 18:37 ] MumbleExpress : "" is not a valid username. Reenter server address <-- this should say re-enter username
[ 18:37 ] MumbleExpress : Enter password
[ 18:37 ] MumbleExpress : Could not connect

**Comment by tomKPZ** [comment]
Fixed in de72cdfa14f70af368fdf2756b642dfe3370073e
