### ISSUE TITLE
Users can crash the server by sending a blank message immediately after entering the password

### ISSUE THREAD

**Issue by tomKPZ** [Jrawke/mumbleExpress#19]

**Comment by Jrawke** [comment]
https://github.com/Jrawke/mumbleExpress/commit/d9f44afd49080935d6dd377bf4bfb80592d7f62e should have fixed this. Can you still reproduce?

**Comment by Jrawke** [comment]
This should be fixed. We make sure the server has an open mumble connection before attempting to send messages now.
