### ISSUE TITLE
"undefeaned" should be "muted"

### ISSUE THREAD

**Issue by tomKPZ** [Jrawke/mumbleExpress#28]
When I mute myself in a mumble desktop client, I see the message "[14:39 ] tom____mac : undeafened"

**Comment by Jrawke** [comment]
https://github.com/Jrawke/mumbleExpress/commit/7c0c8d4b8404631624f1e12788f651f8cca9394d fixed

**Comment by Jrawke** [comment]
actually still small issue

**Comment by Jrawke** [comment]
https://github.com/Jrawke/mumbleExpress/commit/9e215a077a92aedc47eaa520210038d740ec14b9
