### ISSUE TITLE
Users disconnecting don't disappear from channel tree

### ISSUE THREAD

**Issue by tomKPZ** [Jrawke/mumbleExpress#29]

**Comment by Jrawke** [comment]
https://github.com/Jrawke/mumbleExpress/commit/833ac90702458f1c0eabe34d44a304e9010703a9 fixed

**Comment by Jrawke** [comment]
er, https://github.com/Jrawke/mumbleExpress/commit/9e215a077a92aedc47eaa520210038d740ec14b9
