### ISSUE TITLE
Sub Channel Creation

### ISSUE THREAD

**Issue by andreaspeters** [Jrawke/mumbleExpress#32]
Hi @Jrawke ,

first, thanks to your nice html5 mumble client. It's good to use and your code looks clean, I like it. :-)

Well, have a short question. I'm interesting in the feature to create a root subchannel by url query param. So, I tried a whole week to add this feature to your client. But I think I'm to stupid for that. My peace of test code:

```
					client.connection.sendMessage( 'ChannelState', { 
						name: "test"
					});
```
didn't create one. And if I add the parameter parent, I'm getting a error message on the rootScope in the browser. I think u can add this feature much faster then me. :-) Would be nice.

Thanks
Andreas

**Comment by Jrawke** [comment]
Hi @andreaspeters 

I have been busy with work and do not have time to add this feature. However, if you end up implementing this please send a pull request. I would be happy to merge it.

This API documentation might help you
https://github.com/Rantanen/node-mumble/wiki/Channel#user-content-Channel+addSubChannel

Thanks.
