### ISSUE TITLE
automate bower package install

### ISSUE THREAD

**Issue by Jrawke** [Jrawke/mumbleExpress#4]
This issue will be closed when angular-ui-tree (and any other dependency) is no longer statically included

**Comment by Jrawke** [comment]
this should compile the scss too. maybe this can all be accomplished with the tool "grunt"

**Comment by tomKPZ** [comment]
@Jrawke Is this completed?

**Comment by Jrawke** [comment]
not yet unfortunately. Grunt is used to compile the scss and some other things, but I haven't made it install that bower package yet

**Comment by Jrawke** [comment]
https://github.com/Jrawke/mumbleExpress/commit/2392d9b3c83a446ec52ffde1d16a66f1dd15f3a9

I couldn't find an ideal way to do this without the bower.json file, but this is automated in gulp nevertheless.
