### ISSUE TITLE
User can enter erroneous IP addreses such as " " or any nonempty string

### ISSUE THREAD

**Issue by tomKPZ** [Jrawke/mumbleExpress#6]

**Comment by Jrawke** [comment]
[ 18:33 ] MumbleExpress : Enter server address
Input "aoeu". enter
[ 18:34 ] MumbleExpress : Enter port (if blank, will be default of 64738)
enter
[ 18:34 ] MumbleExpress : Enter user name
input "user". enter
[ 18:34 ] MumbleExpress : Enter password
enter
[ 18:34 ] MumbleExpress : Could not connect

**Comment by Jrawke** [comment]
nm, "aoeu" could be on local network.
